import Head from "next/head";

export default function Terms() {
    return (
        <>
            <Head>
                <title>Terms and Policy</title>
                <meta name="description" content="Terms and Policy for Natural Solutions & Neutraceuticals Pvt. Ltd." />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mt-20 px-4 py-8 flex flex-col gap-3 md:max-w-6xl mx-auto">
                <h1 className="text-2xl font-bold">Terms and Policy</h1>

                <h2 className="text-lg font-semibold">Introduction:</h2>
                <p>a) www.nsnpl2health.com is the website shopping platform (referred to as “Platform”) is developed and owned by Natural Solutions & Neutraceuticals PVT. LTD. (hereinafter referred to as “NSNPL”), a company incorporated under the provisions of the Companies Act, 1956, having its registered office at 3rd Floor, A-304, Bonanza, Sahar Plaza Complex, Andheri – Kurla Road, J. B. Nagar, Andheri, East Mumbai, Mumbai Suburban, Maharashtra.</p>

                <p>b) This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a Platform and does not require any physical or digital signatures.</p>

                <p>c) This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the Platform.</p>

                <p>d) For the purpose of these Terms of Use, wherever the context so requires, “You” or “Customer” shall mean any natural or legal person who uses the Platform. NSNPL allows the User to surf the Platform without registering on the Platform. The terms “We”, “Us”, and “Our” shall mean NSNPL.</p>

                <p>e) Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform, including the applicable policies which are incorporated herein by reference. Use of the Platform shall be subject to the policies that are applicable to the Platform. By mere use of the Platform, You shall be contracting with NSNPL and these terms and conditions, including the policies, constitute your binding obligations with NSNPL.</p>

                <p>f) This Platform, including all Materials present (excluding any applicable third-party materials), is the property of NSNPL and is copyrighted and protected by worldwide copyright laws and treaty provisions. You hereby agree to comply with all copyright laws worldwide in your use of this Platform and to prevent any unauthorized copying of the Materials. NSNPL does not grant any express or implied rights under any patents, trademarks, copyrights, or trade secret information.</p>

                <h2 className="text-lg font-semibold">Customer Eligibility:</h2>
                <p>The customer should check and comply with the provisions related to the Indian Contract Act, of 1872 to become a registered customer on the Platform.</p>

                <h2 className="text-lg font-semibold">Registration Obligation:</h2>
                <p>Customers should get registered on the Platform and for registration; they should follow the instructions as visible on the Platform at the time of registration.</p>

                <h2 className="text-lg font-semibold">Communication:</h2>
                <p>When You use the Platform or send emails or other data, information, or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.</p>

                <h2 className="text-lg font-semibold">Posting on Platform:</h2>
                <p>The right to post anything on the Platform is the legal right of NSNPL only. If any third party knowingly or unknowingly breaches this term, then NSNPL will have the right to take legal action as per the prevailing laws of the land.</p>

                <h2 className="text-lg font-semibold">Disclaimer of Warranties and Liability:</h2>
                <p>This Platform, all the Materials and information/content (including but not limited to software), and services included on or otherwise made available to you through this Platform are provided on an “as is” and “as available” basis without any representation or warranties, express or implied, except otherwise specified in writing. Without prejudice to the foregoing paragraph, NSNPL does not warrant that: (i) This Platform will be constantly available, or available at all; or (ii) The information on this Platform is complete, true, accurate, or non-misleading. NSNPL will not be liable to you in any way or in relation to the Materials of, or use of, or otherwise in connection with, the Platform. NSNPL does not warrant that this Platform; information, content, Materials, product (including software) or services included on or otherwise made available to You through the Platform; their servers; or electronic communication sent from us are free of viruses or other harmful components.</p>

                <h2 className="text-lg font-semibold">Indemnity:</h2>
                <p>You shall indemnify and hold harmless NSNPL, its owner, licensee, affiliates, subsidiaries, group companies (as applicable), and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of these Terms of Use, Privacy Policy, and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>

                <h2 className="text-lg font-semibold">Limitation of Damages:</h2>
                <p>In no event shall NSNPL or any of its subsidiaries or affiliates be liable to any entity for any direct, indirect, special, consequential, or other damages (including, without limitation, any lost profits, business interruption, loss of information or programs, or other data on your information handling system) that are related to the use of, or the inability to use, the content, materials, and functions of this Platform or any linked Platform, even if NSNPL is expressly advised of the possibility of such damages.</p>

                <h2 className="text-lg font-semibold">Disclaimer:</h2>
                <p>The Platform may contain inaccuracies and typographical and clerical errors. NSNPL expressly disclaims any obligation(s) to update this Platform or any of the materials on this Platform. NSNPL does not warrant the accuracy or completeness of the Materials or the reliability of any advice, opinion, statement, or other information displayed or distributed through the Platform. You acknowledge that any reliance on any such opinion, advice, statement, memorandum, or information shall be at your sole risk. NSNPL reserves the right, in its sole discretion, to correct any errors or omissions in any portion of the Platform. NSNPL may make any other changes to the Platform, the materials, and the products, programs, services, or prices (if any) described on the Platform at any time without notice. This Platform is for informational purposes and fulfillment of the purposes for which the Platform was developed by NSNPL only and should not be construed as technical advice of any manner.</p>

                <h2 className="text-lg font-semibold">Applicable Law:</h2>
                <p>Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Mumbai, Maharashtra.</p>

                <h2 className="text-lg font-semibold">Contact Us:</h2>
                <p>Please contact us at info@nsnpl2health.com or call +91 7304430089 for any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Platform.</p>
            </main>
        </>
    )
}
